modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="delynxos_wt_mod"
version="1.0.0"
displayName="delynxos wt mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="redst, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.delynxos_wt_mod]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.delynxos_wt_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



